name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.32.5"
      - run: deno check --all ./src/*.ts
      - run: deno lint
      - run: deno test --coverage=cov_profile
      - run: deno coverage cov_profile --lcov --output=cov_profile.lcov
      - uses: codecov/codecov-action@v2
        with:
          files: ./cov_profile.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
